<?php
$z[0]=Array("field","北京网站设计,北京网页设",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","藤设计(www.tengsj.com)建站经验丰富，能为您提供北京网站建设、北京网站制作、北京网站设计和上海网站设计、上海网站建设、上海网站制作两地服务，实现企业互联网一站式建站服务。",77,365);
$z[1][4]['name']="description";
$z[2]=Array("field","中秋节手机专题网站设计",367,438);
$z[2][4]['name']="title";
$z[3]=Array("field","",440,479);
$z[3][4]['name']="writer";
$z[4]=Array("field","",481,520);
$z[4][4]['name']="source";
$z[5]=Array("field","",522,562);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<div style=\"text-align: center;\"><img src=\"/uploads/allimg/c141025/141423425U20-103C4.jpg\" alt=\"手机网站设计\" /></div><div style=\"text-align: center;\"><br /></div><div style=\"text-align: center;\">月圆中秋，藤设计为大家送上节日祝福。您只需要用手机扫描以上二维码即可欣赏到我们为您精心准备的中秋祝福</div><div style=\"text-align: center;\">无论您在哪里，您可能已经与家人团聚，还是忙于工作岗位或还在异地无法回家的朋友，我们都真心的问候您一句：中秋节快乐！<br /></div><div style=\"text-align: center;\"><br /></div><div style=\"text-align: center;\">月是中秋分外明，藤设计把问候遥相寄；</div><div style=\"text-align: center;\">皓月当空洒清辉，中秋良宵念挚心；<br />祝愿您佳节多好运，月圆人圆事事圆！</div><div style=\"text-align: center;\"><br /></div><div style=\"text-align: center;\">如果您觉得藤设计设计的中秋祝福手机专题网站比较不错，您可以用微信分享给您的朋友，让您的朋友也能获取到这份礼物。</div><div style=\"text-align: center;\"><br /></div><div style=\"text-align: center;\"><br /></div>",564,1796);
$z[6][4]['name']="body";
$z[7]=Array("field","",1798,1833);
$z[7][4]['name']="gg";
$z[8]=Array("field","",1835,1870);
$z[8][4]['name']="gx";
$z[9]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",1872,2136);
$z[9][4]['name']="imgurls";
$z[10]=Array("field","/uploads/allimg/c141025/1414234260440-115I9.jpg",2138,2224);
$z[10][4]['name']="litpic";

?>