<li>
                    	        <a href="[field:arcurl/]" target="_blank">
                        	        <em></em>
                        	        <img src="[field:litpic/]" />
                                    <div class="picLText">
                            	        <p>[field:title/]</p>
                                        <span>Hits:    <script src="/plus/count.php?view=yes&aid=[field:id/]&mid=1" type='text/javascript' language="javascript"></script> Date:[field:pubdate function="MyDate('Y',@me)"/]</span>
                                    </div>
                                </a>
                            </li>