{dede:field name='keywords'}北京网站设计,北京网页设{/dede:field}
{dede:field name='description'}藤设计(www.tengsj.com)建站经验丰富，能为您提供北京网站建设、北京网站制作、北京网站设计和上海网站设计、上海网站建设、上海网站制作两地服务，实现企业互联网一站式建站服务。{/dede:field}
{dede:field name='title'}吉凯丽英语培训LOGO和网站设计{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p align="left">吉凯丽教育类机构，LOGO设计直观明了，并且具有独特的艺术美感。它由“吉”中文字母演变成一个运动中的人体作为核心图案标识。其中英文采用正规设计。生动的将教育与用户交流互动的特点转化为视觉形象。<br />色彩运用上，绿色代表健康、清新、责任、朝气的进取精神；运动的人物造型采用有绿到桔黄渐变色，表示着学英语是个让您能成功，无论是就业还是生活上都能有灿烂的“阳光”，同时也为整个标注注入了一股活力。<br />而周围采用立体设计，不仅和人物的渐变色相呼应，更体现了灵动的节奏感。</p><p align="center"><img alt="" src="/uploads/allimg/c141025/1414234523210-15161.jpg" /></p><p align="center"><img alt="" src="/uploads/allimg/c141025/1414234524960-2K50.jpg" /></p><p align="center"><img alt="" src="/uploads/allimg/c141025/1414234526040-3D14.jpg" /></p>{/dede:field}
{dede:field name='gg'}{/dede:field}
{dede:field name='gx'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c141025/141423452DP-42I8.jpg{/dede:field}
