<li>
                                    <a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a>
                                    <div class="navHidden">
                                        <div class="subNav">
                                	        <div class="subNLeft">
                                                 {dede:channel}
                                                        <a href="[field:typelink/]">[field:typename/]</a>
                                                    {/dede:channel}
                                                    
                                            </div>
                                            <div class="subPic">
                                                <img alt="" src="/banner/20130729082259_5407.jpg" /> 
<p>&nbsp;
	
</p>
                                            </div>
                                            <div class="clear"></div>
                                        </div>
                                    </div>
                                </li>