{dede:field name='keywords'}北京网站设计,北京网页设{/dede:field}
{dede:field name='description'}藤设计(www.tengsj.com)建站经验丰富，能为您提供北京网站建设、北京网站制作、北京网站设计和上海网站设计、上海网站建设、上海网站制作两地服务，实现企业互联网一站式建站服务。{/dede:field}
{dede:field name='title'}北京苏伯格林（集团）公司网站设计{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p style="text-align: center;"><img src="/uploads/allimg/c141025/1414234311350-155941.jpg" alt="集团网站首页设计" /></p><p style="text-align: center;">第一眼看到“竭我所能，为你加油”的广告语时，就被这个品牌深深吸引，看上去一句很普通的话，但却贯彻了整个公司的精神。</p><p style="text-align: center;">有多少企业一直追求完美，却疏忽了最简单的语言，这种表达形式非常的深入人心</p><p style="text-align: center;">藤设计为北京苏伯格林（集团）公司设计的中英文混合系统的双语言网站</p><br /><p style="text-align: center;"><img src="/uploads/allimg/c141025/1414234313060-1D642.jpg" alt="关于我们页面设计" /><br /></p><p style="text-align: center;">整站采用简洁大气的设计风格，赢得集团公司的一致认同（现阶段还在测试阶段，还有很多数据不完善，非常抱歉）</p><br /><p style="text-align: center;"><img src="/uploads/allimg/c141025/1414234315250-1LI7.jpg" alt="联系我们页面" /><br /></p><p style="text-align: center;">考虑到集团公司在全国各地区有多个联系方式，所以界面设计采用地标性建筑的特色打造最直观的视觉感受，同时能更亲近当地用户。</p><br /><p style="text-align: center;"><img src="/uploads/allimg/c141025/1414234316450-1Xa6.jpg" alt="业务介绍" /><br /></p><br />{/dede:field}
{dede:field name='gg'}{/dede:field}
{dede:field name='gx'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c141025/141423431J20-1c643.jpg{/dede:field}
