{dede:field name='keywords'}站长之家, WordPress, 个人网{/dede:field}
{dede:field name='description'}WordPress最大的优势在于自由性、开放性。伴随WordPress衍生的各式插件、主题不计其数，因此虽然WordPress是以开源博客平台身份出现的，但只要你愿意，就可以把它打造成任{/dede:field}
{dede:field name='title'}{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p>在博客最火的年代里，我想大家或多或少都听说过一个名为WordPress的东西，它是一款基于PHP和MySQL数据库的开源博客平台，喜欢折腾、喜欢DIY的朋友或许都玩过WordPress。</p>
<p>WordPress最大的优势在于自由性、开放性。伴随WordPress衍生的各式插件、主题不计其数，因此虽然WordPress是以开源博客平台身份出现的，但只要你愿意，就可以把它打造成任何你想要的样子。怎么样？这绝对比在现成的博客或网站或空间里换换皮肤、换几个固定插件要有意思的多吧？</p>
<p><strong>编辑教你打造免费个人网站</strong></p>
<p>我最早接触WordPress是在07年上大学期间，在当时看来，WordPress已经算是非常简单的自主搭建博客平台了，不过以现在的眼光来看，还是有一些门槛的。比如你至少要掌握MySQL数据库的一些知识、还要会用FTP工具、同时还要了解Apache等Web服务软件的使用方式，当然最后你还要花一些费用去租用一个服务器，而最终搭建的WordPress的整体体验好不好，比如打开速度快不快、稳不稳定等，则取决于你愿意花多少钱去租用服务器。</p>
<p>因此可以看出，以往要想玩转WordPress，即便你愿意花钱租用服务器，并且会使用FTP软件，但你至少也要跨过&ldquo;MySQL数据库&rdquo;以及&ldquo;会使用Apache等Web服务软件&rdquo;这两道坎，才可以保证一个WordPress的顺利搭建和运营。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/140923623a50-252F1.jpg" border="0" width="580" /></p>
<p><strong>WordPress是最好玩的开源博客平台</strong></p>
<p>时过境迁，云时代的到来让很多事情都变得简单，渐渐被遗忘的WordPress也迎来了重生的机会。百度云、阿里云、京东云等云服务，都为搭载WordPress提供了傻瓜式的操作环境，但相对来说，京东云擎（JAE）是目前笔者觉得最为简单、最为划算的解决方案，因为它不仅操作简单，而且是完全免费的。</p>
<p>不过在我看来，各类云与WordPress之间总有一种&ldquo;君生我未生，我生君已老&rdquo;的遗憾，在这个以微博、微信为主导的碎片化信息分享时代里，&ldquo;博客&rdquo;二字怎么看怎么都觉得有些古老，但是JAE的免费加上WordPress的开源，我觉得还是具有很高的可玩性。</p>
<p>比如你可以通过WordPress来体验一下当个人站长的乐趣；再比如你可以搭建一个属于你和你爱人的&ldquo;温馨小屋&rdquo;，把你们的照片、日志放到里面；再比如你可以把它做成个人的资源分享网站等等。WordPress的开源性注定让它不会随着时间的洪流被淘汰，在今天它依然是我认为的最简单、最好玩的开源平台，没有之一。</p>
<p>好了，闲话不多说，下面就请各位小伙伴打起精神，随笔者一起来看看如何利用京东云擎（JAE：以下都采用JAE简称）以及WordPress来免费搭建一个属于自己的网站吧！</p>
<p><strong>PS：看到一些朋友部署出现了问题，请确认一下下载下来的WordPress安装包是不是在根目录下打包的，如下图所示：</strong></p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/1409236240210-2A314.png" alt="WordPress 个人网站 Wordpress网站" border="0" width="580" /></p>
<p><strong>安装包打开之后是这个样子的，不要把这些文件放到文件夹里</strong></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c140828/140923623a50-252F1.jpg{/dede:field}
