<?php
$z[0]=Array("field","北京网站设计,北京网页设",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","藤设计(www.tengsj.com)建站经验丰富，能为您提供北京网站建设、北京网站制作、北京网站设计和上海网站设计、上海网站建设、上海网站制作两地服务，实现企业互联网一站式建站服务。",77,365);
$z[1][4]['name']="description";
$z[2]=Array("field","1611美容护肤品网站设计",367,436);
$z[2][4]['name']="title";
$z[3]=Array("field","",438,477);
$z[3][4]['name']="writer";
$z[4]=Array("field","",479,518);
$z[4][4]['name']="source";
$z[5]=Array("field","",520,560);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p style=\"text-align: center;\"><img src=\"/uploads/allimg/c141025/1414234245230-13962.jpg\" alt=\"首页设计\" /></p><p style=\"text-align: center;\">已古典的色彩加上淡淡的肤色，将整个网站变的更加具有视觉效果</p><p style=\"text-align: center;\">用户可以在线购买自己需要的产品，并还可以享受打折优惠</p><p style=\"text-align: center;\"><img src=\"/uploads/allimg/c141025/141423424CZ-2K33.jpg\" alt=\"品牌故事\" /><br /></p><p style=\"text-align: center;\">我们卖的不只是一款又一款的产品，我们也不只是为了做遮丑的的工具，我们将最好的用网站的形式推荐给您</p><p style=\"text-align: center;\">我们是一个品牌，也是一个故事</p><p style=\"text-align: center;\">1611值得信赖</p><p style=\"text-align: center;\"><img src=\"/uploads/allimg/c141025/141423424Q0-31O5.jpg\" alt=\"最新动态界面设计\" /><br /></p><p style=\"text-align: center;\">如果您对我们的产品比较感兴趣，不妨来更细心的了解下我们</p>",562,1620);
$z[6][4]['name']="body";
$z[7]=Array("field","",1622,1657);
$z[7][4]['name']="gg";
$z[8]=Array("field","",1659,1694);
$z[8][4]['name']="gx";
$z[9]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",1696,1960);
$z[9][4]['name']="imgurls";
$z[10]=Array("field","/uploads/allimg/c141025/14142342493F-4K18.jpg",1962,2046);
$z[10][4]['name']="litpic";

?>