<?php
$z[0]=Array("field","北京网站设计,北京网页设",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","藤设计(www.tengsj.com)建站经验丰富，能为您提供北京网站建设、北京网站制作、北京网站设计和上海网站设计、上海网站建设、上海网站制作两地服务，实现企业互联网一站式建站服务。",77,365);
$z[1][4]['name']="description";
$z[2]=Array("field","上海春川建筑劳务网站设计",367,441);
$z[2][4]['name']="title";
$z[3]=Array("field","",443,482);
$z[3][4]['name']="writer";
$z[4]=Array("field","",484,523);
$z[4][4]['name']="source";
$z[5]=Array("field","",525,565);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p style=\"text-align: center;\"><img src=\"/uploads/allimg/c141025/14142342V510-14X9.png\" alt=\"网站首页设计\" /></p><p style=\"text-align: center;\">非常简洁大气的网站效果，整个网站设计将原有的堆积样式完全抛开，并对一家劳务公司而言也是非常有价值的体现，这与同行业相比此类设计更加出众。</p><p style=\"text-align: center;\"><img src=\"/uploads/allimg/c141025/14142342Y0Z-210U.png\" alt=\"企业简介介绍\" /></p><p style=\"text-align: center;\">说自己企业好的文字不需要多，我们根据自己的能力来展示自己，用实力说话（上图是裁切过的，实际网站含有项目列表）</p><p style=\"text-align: center;\"><img src=\"/uploads/allimg/c141025/14142342Z540-3U56.png\" alt=\"案例欣赏\" /></p><p style=\"text-align: center;\">服务不只是喊口号，出制度，而是我们在施工现场的每一个细节表现，用心服务！</p><p style=\"text-align: center;\"><img src=\"/uploads/allimg/c141025/1414234292620-43b2.png\" alt=\"联系方式\" /></p><p style=\"text-align: center;\">我们始终坚持，细节决定成败，我们有能力完成您委托的工作，请联系我们~</p>",567,1782);
$z[6][4]['name']="body";
$z[7]=Array("field","",1784,1819);
$z[7][4]['name']="gg";
$z[8]=Array("field","",1821,1856);
$z[8][4]['name']="gx";
$z[9]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",1858,2122);
$z[9][4]['name']="imgurls";
$z[10]=Array("field","/uploads/allimg/c141025/1414234293A0-55D4.jpg",2124,2208);
$z[10][4]['name']="litpic";

?>