<li class="group">
            <div class="dribbble">
                <div class="dribbble-shot">
                    <div class="dribbble-img">
<a href="[field:arcurl/]"><img alt="[field:title/]" title="[field:title/]" src="[field:litpic/]" height="170" width="275"></a>                    </div>
                </div>
            </div>
            <h2><a rel="contact" class="url" href="[field:arcurl/]">[field:title/]</a></h2>
            <p>[field:description/]...</p>
        </li>