{dede:field name='keywords'}北京网站设计,北京网页设{/dede:field}
{dede:field name='description'}藤设计(www.tengsj.com)建站经验丰富，能为您提供北京网站建设、北京网站制作、北京网站设计和上海网站设计、上海网站建设、上海网站制作两地服务，实现企业互联网一站式建站服务。{/dede:field}
{dede:field name='title'}北京索阳太阳能logo设计{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p align="left">标志的主视觉：整体造型S，射线型设计，节能手段快速、有效<br />形体：面对各种复杂节能系统，我们帮您进行系统整合。提供简单、方便、快捷 能源解决方案<br />颜色：橘红、蓝、黄、绿 ，我们不是冷冰冰的产品服务，而是新能源整管理的解决商<br />整合：索阳在能源管理上是快速有效的<br /></p><p align="center"><img alt="" src="/uploads/allimg/c141025/141423452R30-5F19.jpg" /></p><p align="center"><img alt="" src="/uploads/allimg/c141025/141423452a60-BX5.jpg" /></p>{/dede:field}
{dede:field name='gg'}{/dede:field}
{dede:field name='gx'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c141025/1414234530D0-N614.jpg{/dede:field}
