<?php
$z[0]=Array("field","北京网站设计,北京网页设",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","藤设计(www.tengsj.com)建站经验丰富，能为您提供北京网站建设、北京网站制作、北京网站设计和上海网站设计、上海网站建设、上海网站制作两地服务，实现企业互联网一站式建站服务。",77,365);
$z[1][4]['name']="description";
$z[2]=Array("field","紫芳轩LOGO设计",367,424);
$z[2][4]['name']="title";
$z[3]=Array("field","",426,465);
$z[3][4]['name']="writer";
$z[4]=Array("field","",467,506);
$z[4][4]['name']="source";
$z[5]=Array("field","",508,548);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>中国有着悠久的茶文化，每逢论茶，总与文人骚客联系在一起。<br />这是一种带着书卷气的儒雅，一种淡薄而豁达的人生态度。<br />标志传承了中国书法的苍劲厚重，以新绿的茶芽将书法字形变异，传统而现代。<br />浓厚的文化底蕴和清新醇厚的茶香就这样自然而然地结合在了一起。</p><p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c141025/141423453520-103a0.jpg\" /></p><p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c141025/1414234536410-112948.jpg\" /></p><p align=\"center\"><img alt=\"\" src=\"/uploads/allimg/c141025/141423453I30-12M53.jpg\" /></p>",550,1238);
$z[6][4]['name']="body";
$z[7]=Array("field","",1240,1275);
$z[7][4]['name']="gg";
$z[8]=Array("field","",1277,1312);
$z[8][4]['name']="gx";
$z[9]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",1314,1578);
$z[9][4]['name']="imgurls";
$z[10]=Array("field","/uploads/allimg/c141025/141423453S50-131946.jpg",1580,1666);
$z[10][4]['name']="litpic";

?>