{dede:field name='keywords'}北京网站设计,北京网页设{/dede:field}
{dede:field name='description'}藤设计(www.tengsj.com)建站经验丰富，能为您提供北京网站建设、北京网站制作、北京网站设计和上海网站设计、上海网站建设、上海网站制作两地服务，实现企业互联网一站式建站服务。{/dede:field}
{dede:field name='title'}紫芳轩LOGO设计{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p>中国有着悠久的茶文化，每逢论茶，总与文人骚客联系在一起。<br />这是一种带着书卷气的儒雅，一种淡薄而豁达的人生态度。<br />标志传承了中国书法的苍劲厚重，以新绿的茶芽将书法字形变异，传统而现代。<br />浓厚的文化底蕴和清新醇厚的茶香就这样自然而然地结合在了一起。</p><p align="center"><img alt="" src="/uploads/allimg/c141025/141423453520-103a0.jpg" /></p><p align="center"><img alt="" src="/uploads/allimg/c141025/1414234536410-112948.jpg" /></p><p align="center"><img alt="" src="/uploads/allimg/c141025/141423453I30-12M53.jpg" /></p>{/dede:field}
{dede:field name='gg'}{/dede:field}
{dede:field name='gx'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c141025/141423453S50-131946.jpg{/dede:field}
