<?php
$z[0]=Array("field","北京网站设计,北京网页设",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","藤设计(www.tengsj.com)建站经验丰富，能为您提供北京网站建设、北京网站制作、北京网站设计和上海网站设计、上海网站建设、上海网站制作两地服务，实现企业互联网一站式建站服务。",77,365);
$z[1][4]['name']="description";
$z[2]=Array("field","北京保诺企业OA网站界面设计",367,443);
$z[2][4]['name']="title";
$z[3]=Array("field","",445,484);
$z[3][4]['name']="writer";
$z[4]=Array("field","",486,525);
$z[4][4]['name']="source";
$z[5]=Array("field","",527,567);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p style=\"text-align: center;\"><img src=\"/uploads/allimg/c141025/1414234306120-12M33.jpg\" alt=\"企业内部OA界面\" /></p><p style=\"text-align: center;\">根据北京BioDuro（保诺公司）提供的现有功能进行系统性的调整和界面设计</p><p style=\"text-align: center;\">该OA为企业内部系统，<span style=\"text-align: center;\">保诺</span>员工可以查看企业最新动态和相关活动、在线考勤，<span style=\"text-align: center;\">并且含有人性化提交窗口（员工的建议）</span>等功能</p><p style=\"text-align: center;\"><img src=\"/uploads/allimg/c141025/141423430NP-136446.jpg\" alt=\"登录界面细节处理\" /><br /></p><p style=\"text-align: center;\">上图是局部区域放大展示效果（User Login 细节化处理）</p><p style=\"text-align: center;\">整个网站完全使用CSS框架设计而成，让页面加载更加流畅，杜绝了大量使用图片而影响员工体验。</p><p style=\"text-align: center;\">此界面支持：IE6,IE7,IE8,IE9,FF,360等主流浏览器</p>",569,1640);
$z[6][4]['name']="body";
$z[7]=Array("field","",1642,1677);
$z[7][4]['name']="gg";
$z[8]=Array("field","",1679,1714);
$z[8][4]['name']="gx";
$z[9]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",1716,1980);
$z[9][4]['name']="imgurls";
$z[10]=Array("field","/uploads/allimg/c141025/1414234309240-1450W.jpg",1982,2068);
$z[10][4]['name']="litpic";

?>