{dede:field name='keywords'}北京网站设计,北京网页设{/dede:field}
{dede:field name='description'}藤设计(www.tengsj.com)建站经验丰富，能为您提供北京网站建设、北京网站制作、北京网站设计和上海网站设计、上海网站建设、上海网站制作两地服务，实现企业互联网一站式建站服务。{/dede:field}
{dede:field name='title'}青少年梦基金网站策划及网站设计{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p style="text-align: center;"><img src="/uploads/allimg/c141025/1414234295350-E533.jpg" alt="网站首页设计" /></p><p style="text-align: center;">因为身边有那么一群志愿者在努力，在帮助那些需要帮助的人，所以这个社会变得如此美丽。</p><p style="text-align: center;"><img src="/uploads/allimg/c141025/14142342b250-LD0.jpg" alt="基金会介绍" /></p><p style="text-align: center;">为每个青少年播种梦想、点燃梦想，让更多青少年敢于有梦、勇于追梦、勤于圆梦、让每个青少年都为实现中国梦想增添强大青春能量。</p><p style="text-align: center;"><img src="/uploads/allimg/c141025/14142342c3Z-T915.jpg" alt="梦想平台" /></p><p style="text-align: center;">小纸条，大梦想</p><p style="text-align: center;"><img src="/uploads/allimg/c141025/14142343010P-9E57.jpg" alt="圆梦新闻资讯" /></p><p style="text-align: center;">圆孩子梦想，为他们带去快乐与希望，这个社会不冷漠，用爱关怀！</p><p style="text-align: center;"><img src="/uploads/allimg/c141025/1414234302Q0-10U15.jpg" alt="自愿者报名" /></p><p style="text-align: center;">汇聚和传递爱的力量<br />采集并铸就少年梦想<br />2014，少年梦想基金会志愿者招募；<br />用我们所拥有的，圆孩子所梦想的。</p>{/dede:field}
{dede:field name='gg'}{/dede:field}
{dede:field name='gx'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c141025/1414234304110-113B2.jpg{/dede:field}
