<li>
                	        <div class="newsLTitle">
                    	        <strong><a href="[field:arcurl/]" target="_blank">[field:fulltitle/]</a></strong>
                                <span>关键词：[field:global name='keyword' function='RemoveXSS(@me)'/]</span>
                            </div>
                            <div class="newsLCont">
                    	        <div class="newsLPic">
                        	        <img src="[field:litpic/]" />
                                </div>
                                <div class="newsLAll">
                        	        
[field:description/]……<a href="[field:arcurl/]" target="_blank">查看更多</a>
                                </div>
                                <div class="clear"></div>
                            </div>
                            <div class="newsLDate">[field:pubdate function="MyDate('m-d',@me)"/]</div>
                        </li>