<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="600";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="0";
$z[0][4]['col']="0";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/140829/1-140R9224254.jpg ",93,238);
$z[1][4]['ddimg']="/uploads/allimg/140829/1-140R9224254.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="334";
$z[1][4]['height']="235";
$z[2]=Array("img"," /uploads/allimg/140829/1-140R9224307.jpg ",240,385);
$z[2][4]['ddimg']="/uploads/allimg/140829/1-140R9224307.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="334";
$z[2][4]['height']="235";

?>