<?php
$z[0]=Array("field","网站建设案例,软件开发案",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",77,121);
$z[1][4]['name']="description";
$z[2]=Array("field","海云网站项目网页设计稿",123,194);
$z[2][4]['name']="title";
$z[3]=Array("field","",196,235);
$z[3][4]['name']="writer";
$z[4]=Array("field","",237,276);
$z[4][4]['name']="source";
$z[5]=Array("field","",278,315);
$z[5][4]['name']="body";
$z[6]=Array("field","",317,352);
$z[6][4]['name']="gg";
$z[7]=Array("field","",354,389);
$z[7][4]['name']="gx";
$z[8]=Array("field","",391,431);
$z[8][4]['name']="pubdate";
$z[9]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",433,697);
$z[9][4]['name']="imgurls";
$z[10]=Array("field","/uploads/allimg/c140829/14093163Z230-15152.jpg",699,784);
$z[10][4]['name']="litpic";

?>