
<field:company itemname="公司名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:company>

<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:mail itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mail>

<field:phone itemname="手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:list1 itemname="需要的服务" autofield="1" type="checkbox" isnull="true" default="建设全新的企业网站,现有网站改版,界面设计与美化,网站优化及管理,VI/平面设计 
"  maxlength="250" page="">
</field:list1>
