
{dede:noteinfo notename="½¨Õ¾¾­Ñé" channelid="1" macthtype="string"
    refurl="http://" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.chinaz.com/web/exp/(*).shtml"
startid="1" endid="5" addv="1" urlrule="area" musthas="2014"
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="m-newlist">{/dede:areastart}
    {dede:areaend}<div class="m-page ">{/dede:areaend}
{/dede:listrule}

