{dede:field name='keywords'}站长之家, 思源黑体, 思源{/dede:field}
{dede:field name='description'}七月初我们介绍过“思源黑体”，一款由 Adobe 和 Google 共同合作的开源字型，提供七种字型粗细设置，由最细的 ExtraLight 至最粗的 Heavy，并可为日文、韩文、繁体中文和{/dede:field}
{dede:field name='title'}{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/14092362030P-19136.png" border="0" width="640" alt="思源黑体 思源黑体下载 谷歌Chrome" /></p>
<p>七月初我们介绍过&ldquo;<a href="http://www.chinaz.com/tags/siyuanheitixiazai.shtml" target="_blank">思源黑体</a>&rdquo;，一款由 Adobe 和 Google 共同合作的开源字型，提供七种字型粗细设置，由最细的 ExtraLight 至最粗的 Heavy，并可为日文、韩文、繁体中文和简体中文提供完整支援，整套字型一共超过五十万个字符，是一个庞大且完整的字型组。</p>
<p>这款字型的设计初衷就是希望能保留传统无衬线字型的优雅，即使经过简化，依然能提供极高的文字可读性，很适合用於电子书、文字较多的区块，当然也适用於浏览器。</p>
<p>我目前已经把经常使用的 Blog 离线编辑器和手边的浏览器都换上 Noto Sans 字型，使用一段时间后发现比原来预设的字型更容易阅读，字距看起来也很舒服，昨天介绍过如何将 Mac 介面的预设字型换成思源黑体，本文会教你如何将 Google Chrome 或 Firefox 浏览器字型改为思源黑体。</p>
<p><strong>思源黑体下载地址：</strong><a href="http://font.chinaz.com/140717378230.htm" target="_blank">http://font.chinaz.com/140717378230.htm</a></p>
<p><strong>如何将 Google 浏览器字型改为思源黑体？</strong></p>
<p><strong>Step 1</strong></p>
<p>首先，你必须先至 Google Noto Sans 网页下载思源正体繁体字型，并将它安装到电脑。这款字型即为思源黑体，只不过在 Google 是以 Noto Sans 名称释出。</p>
<p>开启 Advanced Font Settings 浏览器扩充功能页面，点选右上角的&ldquo;&nbsp; 免费&rdquo;安装。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/1409236203H0-21342.png" border="0" width="640" alt="思源黑体 思源黑体下载 谷歌Chrome" /></p>
<p><strong>Step 2</strong></p>
<p>安装后打开 Google浏览器设置，开启&ldquo;进阶设置&rdquo;后找到网页内容的&ldquo;自订字型&rdquo;，点选最下方的&ldquo;进阶字型设置&rdquo;即可开啟 Advanced Font Settings 设置画面。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/1409236204240-3Y56.png" border="0" width="640" alt="思源黑体 思源黑体下载 谷歌Chrome" /></p>
<p><strong>Step 3</strong></p>
<p>在进阶字型设置裡，可针对不同的语系来更换字型，先从 Script 里选择语系，切换至繁体中文后再把 Standard、Serif 及 Sans-Serif 设置成「Noto Sans T Chinese」。</p>
<p>Traditional Han：繁体中文 Simplified Han：简体中文 Japanese：日文 Hangul：韩文</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/140923620460-4M26.png" border="0" width="640" alt="思源黑体 思源黑体下载 谷歌Chrome" /></p>
<p><strong>Step 4</strong></p>
<p>最后按下最下方的 Apply Settings 保存设置。如果要将设置返回预设值，可以点选另外两个按钮直接还原，相当方便。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/14092362051Z-51I7.png" border="0" width="640" alt="思源黑体 思源黑体下载 谷歌Chrome" /></p>
<p>若你是使用 Firefox 浏览器的话，无须安装其他扩充功能，从选项 -&gt; 内容里可以直接设置你要使用的预设字型，将它改为 Noto Sans T Chinese 即可使用思源黑体作为预设字型。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/1409236205S0-64H5.png" border="0" width="640" alt="思源黑体 思源黑体下载 谷歌Chrome" /></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c140828/14092362030P-19136.png{/dede:field}
