{dede:noteinfo notename="案例展示" channelid="2" macthtype="string"
refurl="http://" sourcelang="gb2312" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://www.rdxc.net/list.php?catid=40{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<ul class="lb_case m_t20">{/dede:areastart}
    {dede:areaend}<p id="pages">{/dede:areaend}
{/dede:listrule}
