<?php
$z[0]=Array("field","北京网站设计,北京网页设",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","藤设计(www.tengsj.com)建站经验丰富，能为您提供北京网站建设、北京网站制作、北京网站设计和上海网站设计、上海网站建设、上海网站制作两地服务，实现企业互联网一站式建站服务。",77,365);
$z[1][4]['name']="description";
$z[2]=Array("field","青海上捷LOGO设计",367,427);
$z[2][4]['name']="title";
$z[3]=Array("field","",429,468);
$z[3][4]['name']="writer";
$z[4]=Array("field","",470,509);
$z[4][4]['name']="source";
$z[5]=Array("field","",511,551);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p style=\"text-align: center;\"><img src=\"/uploads/allimg/c141025/141423455G60-109B7.jpg\" alt=\"青海上捷节能设备有限公司设计的所有LOGO图案\" /></p><p style=\"text-align: center;\">无数稿LOGO后，最后商定使用已电池为图像的设计方案</p><p style=\"text-align: center;\"><img src=\"/uploads/allimg/c141025/1414234559320-111442.jpg\" alt=\"手提袋效果\" /><br /></p><p style=\"text-align: center;\">LOGO在手提袋上的应用效果</p><p style=\"text-align: center;\"><img src=\"/uploads/allimg/c141025/14142345604Z-121056.jpg\" alt=\"信纸、名片、胸卡设计\" /><br /></p><p style=\"text-align: center;\">同时也为名片、胸卡、信纸等给出了相关应用方案</p><p style=\"text-align: center;\"><img src=\"/uploads/allimg/c141025/1414234561440-139315.jpg\" alt=\"企业户外效果\" /><br /></p><p style=\"text-align: center;\">将企业形象应用至门口形象墙效果，方便用户直接观看到企业LOGO，从而加深其品牌印象。</p><p><br /></p>",553,1586);
$z[6][4]['name']="body";
$z[7]=Array("field","",1588,1623);
$z[7][4]['name']="gg";
$z[8]=Array("field","",1625,1660);
$z[8][4]['name']="gx";
$z[9]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",1662,1926);
$z[9][4]['name']="imgurls";
$z[10]=Array("field","/uploads/allimg/c141025/1414234562B0-145Y4.jpg",1928,2013);
$z[10][4]['name']="litpic";

?>