{dede:field name='keywords'}北京网站设计,北京网页设{/dede:field}
{dede:field name='description'}藤设计(www.tengsj.com)建站经验丰富，能为您提供北京网站建设、北京网站制作、北京网站设计和上海网站设计、上海网站建设、上海网站制作两地服务，实现企业互联网一站式建站服务。{/dede:field}
{dede:field name='title'}青海上捷LOGO设计{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p style="text-align: center;"><img src="/uploads/allimg/c141025/141423455G60-109B7.jpg" alt="青海上捷节能设备有限公司设计的所有LOGO图案" /></p><p style="text-align: center;">无数稿LOGO后，最后商定使用已电池为图像的设计方案</p><p style="text-align: center;"><img src="/uploads/allimg/c141025/1414234559320-111442.jpg" alt="手提袋效果" /><br /></p><p style="text-align: center;">LOGO在手提袋上的应用效果</p><p style="text-align: center;"><img src="/uploads/allimg/c141025/14142345604Z-121056.jpg" alt="信纸、名片、胸卡设计" /><br /></p><p style="text-align: center;">同时也为名片、胸卡、信纸等给出了相关应用方案</p><p style="text-align: center;"><img src="/uploads/allimg/c141025/1414234561440-139315.jpg" alt="企业户外效果" /><br /></p><p style="text-align: center;">将企业形象应用至门口形象墙效果，方便用户直接观看到企业LOGO，从而加深其品牌印象。</p><p><br /></p>{/dede:field}
{dede:field name='gg'}{/dede:field}
{dede:field name='gx'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c141025/1414234562B0-145Y4.jpg{/dede:field}
