<?php
$z[0]=Array("sppage","",2,61);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.chinaz.com/web/2014/0822/364765.shtml",63,146);
$z[2]=Array("keywordtrim","",148,185);
$z[3]=Array("descriptiontrim","",187,232);
$z[4]=Array("item","\r\n   {dede:match}<h1 class=\"post-title\">[内容]</h1>  \r\n\r\n<div class=\"post-meta f-cb\">{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",234,443);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",443,583);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",583,723);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",723,864);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}<div class=\"u-postcontent cz\" id=\"ctrlfscont\">[内容]<p><strong>注：</strong>相关网站建设技巧阅读请移步到{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",864,1126);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>