<dl class="new_list">
            <dt><a href="[field:arcurl/]"><img alt="[field:title/]" title="[field:title/]" src="[field:litpic/]" height="54" width="87"></a></dt>
            <dd>
              <h2><span class="data">[field:pubdate function="MyDate('m-d',@me)"/]</span><a href="[field:arcurl/]">[field:title/]</a></h2>
              <p>[field:description/]...</p>
            </dd>
          </dl>