{dede:field name='keywords'}北京网站设计,北京网页设{/dede:field}
{dede:field name='description'}藤设计(www.tengsj.com)建站经验丰富，能为您提供北京网站建设、北京网站制作、北京网站设计和上海网站设计、上海网站建设、上海网站制作两地服务，实现企业互联网一站式建站服务。{/dede:field}
{dede:field name='title'}HDHS净心失眠枕名片设计{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p>普普通通的一张名片，进行市场策划和包装，充分利用了互联网的优势，把二维码印刷到了名片里，让智能手机可以直接扫描二维码直接访问企业网站，并且把网站的兑换现金券功能加入进去，将名片信息转为虚拟货币，让名片更加值钱。</p><p>获得一张名片，您相当获得了100元现金的额度，让您在购买产品的时候能抵一部分现金，每次购买最多可抵500元的支付现金。</p><p align="center"><img src="/uploads/allimg/c141025/141423454450-11345.jpg" alt="" /></p>{/dede:field}
{dede:field name='gg'}{/dede:field}
{dede:field name='gx'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c141025/141423454B40-2W20.jpg{/dede:field}
