<?php
$z[0]=Array("field","北京纽瀚斯管理咨询有限",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","北京纽瀚斯管理咨询有限公司",76,159);
$z[1][4]['name']="description";
$z[2]=Array("field","",161,199);
$z[2][4]['name']="title";
$z[3]=Array("field","",201,240);
$z[3][4]['name']="writer";
$z[4]=Array("field","",242,281);
$z[4][4]['name']="source";
$z[5]=Array("field","",283,320);
$z[5][4]['name']="body";
$z[6]=Array("field","",322,357);
$z[6][4]['name']="gg";
$z[7]=Array("field","",359,394);
$z[7][4]['name']="gx";
$z[8]=Array("field","",396,436);
$z[8][4]['name']="pubdate";
$z[9]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",438,702);
$z[9][4]['name']="imgurls";
$z[10]=Array("field","",704,743);
$z[10][4]['name']="litpic";

?>