{dede:field name='keywords'}站长之家, 品牌形象, 品牌{/dede:field}
{dede:field name='description'}可口可乐、美国富国银行和Basecamp都是通过讲故事和内容营销来支撑品牌背后的承诺。内容营销不仅能够促进销售，且有利于塑造品牌形象。{/dede:field}
{dede:field name='title'}{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p><strong>导语：</strong>可口可乐、美国富国银行和Basecamp都是通过讲故事和内容营销来支撑品牌背后的承诺。内容营销不仅能够促进销售，且有利于塑造品牌形象。</p>
<p>内容营销不仅能够促进销售，而且有利于塑造品牌形象。B2B营销者运用内容带动需求，引领潮流。IBM正是凭借在&ldquo;智慧星球&rdquo;内容和管理层报告方面做的大量努力来进行内容营销的。一部分品牌正在拓展思路，考虑如何运用内容交流品牌和商业活动。除了&ldquo;媒体演播室&rdquo;，品牌还利用新兴的社交媒体，以一种非常巧妙的方式讲述故事和制作多媒体。很长时间以来，&ldquo;思科新闻工作室&rdquo;一度被认为是企业媒体网站的典范。这种深远的影响力保持至今。除此之外，可口可乐、美国富国银行(WELLS FARGO)和Basecamp，这三个品牌也做了很多有趣的工作，值得我们研究。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/14092361O040-49232.jpg" alt="品牌形象 品牌营销 内容营销" border="0" /></p>
<p style="text-align: center;"><strong>可口可乐旅程(Coca-Cola Journeys)</strong></p>
<p>Ashley Brown及其团队已经成功为企业品牌创建了一个名为&ldquo;可口可乐旅程&rdquo;的故事讲述平台。通过精巧的编辑，你将会发现这些故事在&ldquo;大图滚动栏&rdquo;中循环放映：</p>
<p>&bull; 如何准备一顿简单的母亲节早中餐&mdash;&mdash;一个简单的流程就能切实帮助到我们这些想要报答母亲，却又对如何下厨房一无所知的人。</p>
<p>&bull; 1886年5月8日：一个新主意的诞生日 &mdash;&mdash;回顾可口可乐从最初在雅各布的化学实验室诞生至今的发展历程</p>
<p>&bull; 完美的镜头: 可口可乐的快乐标杆&mdash;&mdash;这一雄心勃勃的艺术项目是由巴西和阿根廷艺术家设计的，汇集了成千上万的剪贴画拼合而成的海报艺术。</p>
<p>&ldquo;旅程&rdquo;关注的重点非常清晰：公司新闻资讯的最新动态，社会地位日益上升的女性，水资源议题，以及当前2014年世界杯的冠名赞助。内容也涵盖了饮食和音乐。这些都反映了一种向更为生活化的内容的转变&mdash;&mdash;这也是他们从实践中学到的重点。品牌主页简单汇集了比如你在芬达的社交媒体渠道所找到的内容。</p>
<p>&ldquo;旅程&rdquo;中有大量的内容。你还可以通过Unbotteled Blog了解幕后的传播团队，阅读网站推荐的精选文章。</p>
<p>&ldquo;Contently&rdquo;是一个讲故事的平台(内容营销分享平台), 作为可口可乐的合作者，在其品牌战略中提供了极为有用的视角。</p>
<p>据&ldquo;旅程&rdquo;的联合主编Jay Moye透露，2013年，&ldquo;旅程&rdquo;总共发表了1200篇文章，共吸引了131，000,000名网民参与，平均每位网民花费4分40秒的时间在每篇文章的阅读上，这是一个让人印象深刻的数据。通过JourneyOn(交流方会议)，可口可乐全球团队试着将运营秘籍传递给已经各自上线&ldquo;旅程&rdquo;以及那些在未来几个月将会启动&ldquo;旅程&rdquo;的八个国家，包括英国，爱尔兰，西班牙，法国，意大利，奥地利，尼日利亚和肯尼亚。</p>
<p><strong>团队</strong></p>
<p>可口可乐的&ldquo;旅程&rdquo;团队由Ashley Brown&mdash;&mdash;这位年仅35岁的数字传播和社交媒体总监负责。正是Ashley Brown将可口可乐从广告时代带入数字时代的。&ldquo;旅程&rdquo;由Moye和前电视记者Ashley Callahan共同管理。团队的工作人员还包括社会化媒体编辑、平面设计师和分析师等人。来自亚特兰大的视频组负责录制&ldquo;旅程&rdquo;的影像。团队依靠自由职业者，比如作家，摄影师等人，为非可乐产品本身方面的内容服务，比如通过Contently(内容营销分享平台)来展现可口可乐公司的招聘和管理机制。</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c140828/14092361O040-49232.jpg{/dede:field}
