
<field:company itemname="公司名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:company>

<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:mail itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mail>

<field:phone itemname="手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:list1 itemname="需要的服务" autofield="1" type="checkbox" isnull="true" default="建设全新的企业网站,现有网站改版,界面设计与美化,网站优化及管理,VI/平面设计 
"  maxlength="250" page="">
</field:list1>

<field:list2 itemname="您最关注的地方" autofield="1" type="checkbox" isnull="true" default="对功能需求比较高,对设计创意要求比较高,需要可以购物支付,搜索引擎排名"  maxlength="250" page="">
</field:list2>

<field:list3 itemname="预算" autofield="1" type="radio" isnull="true" default="3000~6000,6千~1万,1万~2万,2万~5万,需要招投标 
"  maxlength="250" page="">
</field:list3>

<field:content itemname="需求" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:content>
