
<field:company itemname="公司名称" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:company>

<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:mail itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:mail>

<field:phone itemname="手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>
