{dede:field name='keywords'}欧洲旅游,欧洲旅行,欧洲深{/dede:field}
{dede:field name='description'}趣欧洲旅游网是北京天马假期国际旅行社旗下网站，专注欧洲旅游，个性旅行，小元素旅游，小团体旅游，深度欧洲旅行等业务，咨询电话：4006 800 370{/dede:field}
{dede:field name='title'}{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='gg'}{/dede:field}
{dede:field name='gx'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}{/dede:field}
{dede:field name='litpic'}{/dede:field}
