<?php
$z[0]=Array("field","欧洲旅游,欧洲旅行,欧洲深",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","趣欧洲旅游网是北京天马假期国际旅行社旗下网站，专注欧洲旅游，个性旅行，小元素旅游，小团体旅游，深度欧洲旅行等业务，咨询电话：4006 800 370",78,320);
$z[1][4]['name']="description";
$z[2]=Array("field","",322,360);
$z[2][4]['name']="title";
$z[3]=Array("field","",362,401);
$z[3][4]['name']="writer";
$z[4]=Array("field","",403,442);
$z[4][4]['name']="source";
$z[5]=Array("field","",444,481);
$z[5][4]['name']="body";
$z[6]=Array("field","",483,518);
$z[6][4]['name']="gg";
$z[7]=Array("field","",520,555);
$z[7][4]['name']="gx";
$z[8]=Array("field","",557,597);
$z[8][4]['name']="pubdate";
$z[9]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",599,863);
$z[9][4]['name']="imgurls";
$z[10]=Array("field","",865,904);
$z[10][4]['name']="litpic";

?>