{dede:field name='keywords'}站长之家, 约会网站, OkC{/dede:field}
{dede:field name='description'}OkCupid是国外一家非常受欢迎的约会网站，他们也有自己的App应用。本文摘自其网站博客，作者为该公司联合创始人Christian Rudder。{/dede:field}
{dede:field name='title'}{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p>&nbsp;OkCupid是国外一家非常受欢迎的约会网站，他们也有自己的App应用。本文摘自其网站博客，作者为该公司联合创始人Christian Rudder。</p>
<p>我是第一个这么说的人：我们会变得非常受欢迎，我们会为很多很多人牵红线，我们会实现好多好多事情。不过OkCupid公司貌似并不是真正知道自己在干什么，当然，其他的网站可能也不知道。我们所做的事情，之前并没有多少人做过，因此行业经验不多，而且也没有什么蓝图之类的可供参考。其实我们大多数的想法创意都很糟糕，而且即便有些还算可以的想法，实际上也完全可以做的更好。那么如何解决上述种种问题呢?答案就是要做实验。实验能让你了解任何事情，比如下面这张图，这位年轻的小孩儿想要做实验看看土豆会不会哭。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/1409236235030-1W437.png" border="0" alt="约会网站 OkCupid 网站运营" /></p>
<p>但是最近我们注意到，人们不喜欢被实验，比如之前Facebook在推出他们的news feed时，也在用户身上进行了&ldquo;实验&rdquo;，但结果却遭到了人们的反感，而且这件事儿甚至把美国联邦贸易委员会(FTC)都牵扯了进去。但是猜猜看怎么着，每个人，PS.如果你使用互联网的话，每个人其实都是实验的对象，甚至在某些时候同一个人还可能会是数百个实验的对象，几乎每个网站都这么干过，否则哪儿来那么多成功的网站呢?</p>
<p>在此，我就向大家介绍一下OkCupid之前做过的一些非常有趣的实验吧。</p>
<p><strong>实验一：爱情是盲目的呢?还是应该有目标呢?</strong></p>
<p>OkCupid公司已经创建了有十年了，我们这家公司的缩影可以用一句老话来形容，那就是进两步，退一步。之前我们有了一个极具创意的想法，想要创建一款能够用于相亲的App应用，于是乎我们花了一年半时间专心打造这款应用，但是结果却事与愿违，它在苹果的App Store上只待了六个月就被下架了。</p>
<p>当然啦，谁叫我们OkCupid公司里都是&ldquo;天才&rdquo;呢。在发布这款应用当天，我们决定要庆祝一下，在2013年1月15日，我们把它定为&ldquo;爱情是盲目日&rdquo;，并且我们非常大胆地决定做一个实验，把OkCupid上面的所有照片都删除了。</p>
<p>在&ldquo;庆祝&rdquo;期间，我们网站的所有指标都下跌了，如下图所示：</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/1409236235C0-19C24.png" border="0" alt="约会网站 OkCupid 网站运营" /></p>
<p>但是如果把&ldquo;爱情是盲目日&rdquo;与一个普通的星期二相比较的话，我们发现了一些有趣的事情，在我们网站和应用上没有照片的七个小时里：</p>
<blockquote>
<p>1、人们首次回复短消息的频率的速度比平时上升了44%。</p>
<p>2、人们彼此的对话内容变得更加深层次。</p>
<p>3、人们彼此交换联系信息(包括手机号码和电子邮件)的频率也变得更快。</p>
<p>4、简而言之，OkCupid运作的反而更好了。</p>
</blockquote>
<p>我们在做实验的当天下午四点，把所有的照片都恢复了，当时，处于在与对方进行&ldquo;盲目的&rdquo;交流对话过程中的人一共有2200人，然而当大家看到彼此的照片之后，很快这些对话慢慢地消失了。好事儿都溜走了，当然啦，坏事儿也随风而去了。这种感觉，就像是在午夜的酒吧里，忽然把所有的灯光都打开了。下图是我们恢复用户照片之后，对话时长图，从左向右看会发现，相亲对象彼此的对话时长变得越来越短了。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/1409236235930-20YO.png" border="0" alt="约会网站 OkCupid 网站运营" /></p>
<p>这个实验让我感到非常好奇，于是，我又去查看了一些用户数据，这些用户都是真实在使用我们的相亲App应用的，很快，我发现了一件简单的事情，一旦他们真正彼此相爱，并且开始约会，他们就会非常开心，而且彼此的伴侣究竟是不是长得好看，似乎已经变得不再重要了。下图是女性对约会对象的长相关注比较(实际上男性和女性在这个问题上的看法非常相似)：</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/1409236236220-21Z26.png" border="0" alt="约会网站 OkCupid 网站运营" /></p>
<p>奇怪的是，我还发现了一件事儿。那些长相更加好看的女性，在约会中似乎并不快乐。而从我的实际经验来看，那些喜欢泡妞的帅哥猛男也往往都是&ldquo;混蛋&rdquo;。可能这么解释还不够清楚，让我们换句话来说吧。长相好看的女性，通常会比较&ldquo;冷&rdquo;，如果有人给她们发消息，她们一般都不会回复。而长相较帅的男性，往往都比较热情，如果有人给他们发消息，他们则会积极回复。实际上，用户的线上反应也印证了上述观点，如下图所示，</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/140923623F50-221F2.png" border="0" alt="约会网站 OkCupid 网站运营" /></p>
<p>基本上来说，人们其实还是非常&ldquo;肤浅&rdquo;的，因为他们一般都会受到技术的影响。</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c140828/1409236235030-1W437.png{/dede:field}
