<?php
$z[0]=Array("noteinfo","",0,167);
$z[0][4]['notename']="案例展示";
$z[0][4]['channelid']="2";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}http://www.tengsj.com/cases/type/4.html{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<ol class=\"dribbbles group\">{/dede:areastart}\r\n    {dede:areaend}</ol>\r\n      <div class=\"cl\"></div>{/dede:areaend}\r\n",169,635);
$z[1][4]['sourcetype']="hand";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://";
$z[1][4]['startid']="1";
$z[1][4]['endid']="";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>