{dede:noteinfo notename="案例展示" channelid="2" macthtype="string"
    refurl="http://" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area" musthas=""
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://www.tengsj.com/cases/type/4.html{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<ol class="dribbbles group">{/dede:areastart}
    {dede:areaend}</ol>
      <div class="cl"></div>{/dede:areaend}
{/dede:listrule}
