{dede:field name='keywords'}站长之家, 网站域名, 域名{/dede:field}
{dede:field name='description'}每天我们都访问各种网站，从谷歌到百度，从网易到新浪……我们记住了很多网站的域名。有一些人会事先抢注某些域名，而后希望使用该域名的个人或者公司由于域名已被抢注，如{/dede:field}
{dede:field name='title'}{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/14092362153Z-143K.jpg" alt="网站域名 域名投资 Sex.com 域名抢注" border="0" width="642" title="logo.jpg" hspace="0" vspace="0" height="294" style="width: 580px; height: 294px;" /></p>
<p>作者：Alyson Shontell &nbsp;翻译：翛凌 &nbsp;原文：Entrepreneur</p>
<p>每天我们都访问各种网站，从谷歌到百度，从网易到新浪&hellip;&hellip;我们记住了很多网站的域名。有一些人会事先抢注某些域名，而后希望使用该域名的个人或者公司由于域名已被抢注，如果仍旧希望使用这些域名，就必须向这些已抢注域名的人支付一笔费用。不过，域名究竟能有多值钱？</p>
<p><strong>域名究竟能有多值钱？</strong></p>
<p>据估计，世界上有超过 500 个 URL 地址的交易价格超过 100 万美元。我们列举出了一些价格不菲的域名地址。这些域名有些刚成交不久，有些已经成交过一段时间。</p>
<p>不出意料的，和 sex 有关的一些域名，以及和 gambling 有关的一些域名相当值钱。不过让我们看看其他的一些域名吧。域名成交价由低到高排列。</p>
<p>注意：我们只列出 2003 年以后成交的域名，因为 2003 年之前的域名成交价格没有办法得到验证。为保证数据的真实性，即使之前有些网站被爆成交价格不菲，我们也不将它们列入其中。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/140923621DZ-23316.png" alt="网站域名 域名投资 Sex.com 域名抢注" border="0" width="642" title="mm.png" hspace="0" vspace="0" height="223" style="width: 580px; height: 223px;" /></p>
<p><strong>MM.com&mdash;&mdash;成交价 120 万美元</strong></p>
<p>成交日期：2014 年 7 月</p>
<p>MM.com 在 2014 年 7 月售出了 120 万美元的高价。Sedo 公司从杭州多买公司手中购得该域名。这个中国公司实际上专注于抢注一些网站。它曾持有一些诸如 Game.com、JZ.com 以及 4.cn 之类的域名。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/1409236219A0-31J3.jpg" alt="网站域名 域名投资 Sex.com 域名抢注" border="0" width="642" title="ebet.jpg" hspace="0" vspace="0" height="369" style="width: 580px; height: 320px;" /></p>
<p><strong>eBet.com&mdash;&mdash;成交价 135 万美元</strong></p>
<p>成交日期：2013 年 10 月</p>
<p>这个域名由一位名叫 Rick 的人于 1996 年抢注，之后他一直不售出该域名。直到 2013 年 9 月，他最终同意售出该域名。</p>
<p>Rick 在他的博客上写道：「Network Solutions 在 8 月 29 日联系我，希望用 5 万美元从我这里购得该域名。我在最开始和以前一样没认真考虑这个问题，给 Network Solutions 报价 180 万美元后，我便继续回到日常生活中，继续做我的生意。在 9 月 3 日，买家回复我说可以支付我 100 万美元。所以我想，何不努力达成一个双方都可以接受的价格，而后干脆卖了这个域名得了。所以我回复他们 135 万美元的价格，告诉他们这是我可以接受的底线。之后我没有得到任何回复&mdash;&mdash;直到 9 月 16 日。他们接受了我的报价！」</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/1409236220Z-4A25.jpg" alt="网站域名 域名投资 Sex.com 域名抢注" border="0" width="642" title="1406214427-million-dollar-urls-most-expensive-domain-names-of-all-time-cameras.jpg" hspace="0" vspace="0" height="369" style="width: 580px; height: 320px;" /></p>
<p><strong>Cameras.com&mdash;&mdash;成交价 150 万美元</strong></p>
<p>成交年份：2006 年</p>
<p>DN Journal 曾在 2006 年报道，「cameras.com 这一域名曾吸引了包括 moniker.com 和 T.R.A.F.F.I.C East Conference 在内的多家公司的竞争。」「竞价的获胜者 Sig Solares，是 Parked.com 的 CEO。他提出了 150 万美元的价格，并且成功获得了这个域名。」</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/14092362223Z-5ab.jpg" alt="网站域名 域名投资 Sex.com 域名抢注" border="0" width="642" title="1406214686-million-dollar-urls-most-expensive-domain-names-of-all-time-saint-basil-cathedral.jpg" hspace="0" vspace="0" height="369" style="width: 580px; height: 320px;" /></p>
<p><strong>Russia.com&mdash;&mdash;成交价 150 万美元</strong></p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/1409236223230-CS5.jpg" alt="网站域名 域名投资 Sex.com 域名抢注" border="0" width="642" title="1406214870-million-dollar-urls-most-expensive-domain-names-of-all-time-tandberg.jpg" hspace="0" vspace="0" height="369" style="width: 580px; height: 320px;" /></p>
<p><strong>Tandberg.com&mdash;&mdash;成交价 150 万美元</strong></p>
<p>成交年份：2007 年</p>
<p>DJ Journal 在该域名成交之后曾这样介绍：「Tandberg Data 是一家全球领先的提供备份和存档方案的供应商和生产商。这个公司决定花钱从 Tandberg 购买来这个域名。之前持有 Tandberg.com 域名的 Tandberg 公司是一家提供视觉交流产品服务的全球领先的公司，总部在纽约和挪威都有。」</p>
<p>虽然成交在 2006 年 12 月就已达成，不过在 2007 年初才公布。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/1409236223R0-O4Z.jpg" alt="网站域名 域名投资 Sex.com 域名抢注" border="0" width="642" title="1406214990-million-dollar-urls-most-expensive-domain-names-of-all-time-ticket.jpg" hspace="0" vspace="0" height="369" style="width: 580px; height: 320px;" /></p>
<p><strong>Ticket.com&mdash;&mdash;成交价 152 万 5 千美元</strong></p>
<p>成交年份：2009 年</p>
<p>该域名于 2009 年 10 月成交。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/140923622HZ-T153.jpg" alt="网站域名 域名投资 Sex.com 域名抢注" border="0" width="642" title="1406215207-million-dollar-urls-most-expensive-domain-names-of-all-time-datarecovery.jpg" hspace="0" vspace="0" height="369" style="width: 580px; height: 320px;" /></p>
<p><strong>DataRecovery.com&mdash;&mdash;成交价 165 万 9 千美元</strong></p>
<p>成交年份：2008 年</p>
<p>Minnesota』s Associated Computer 公司在 2008 年 2 月 1 日将该域名卖给了 ESS Data Recovery 公司。之前 ESS 花了很长时间，希望能够购得该域名。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/140923622M60-c3D.jpg" alt="网站域名 域名投资 Sex.com 域名抢注" border="0" width="642" title="1406215306-million-dollar-urls-most-expensive-domain-names-of-all-time-auction.jpg" hspace="0" vspace="0" height="369" style="width: 580px; height: 320px;" /></p>
<p><strong>Auction.com&mdash;&mdash;成交价 170 万美元</strong></p>
<p>成交年份：2009 年</p>
<p>之前曾经有传言，说 Auction.com 域名卖到了 250 万美元。不过最终购得该域名的 Real Estate Disposition Corp 公司声明，成交价为 170 万美元。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/140923622R50-10V33.jpg" alt="网站域名 域名投资 Sex.com 域名抢注" border="0" width="642" title="1406215478-million-dollar-urls-most-expensive-domain-names-of-all-time-dating.jpg" hspace="0" vspace="0" height="369" style="width: 580px; height: 320px;" /></p>
<p><strong>Dating.com&mdash;&mdash;成交价 175 万美元</strong></p>
<p>成交年份：2010 年</p>
<p>Dating.com 在 2012 年 5 月的 DOMAINFest 拍卖会上再度出现。那次拍卖会第二高的价格出现在 Boardgames.com 域名上，该域名要价 45 万美元。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/140923622VZ-11QC.jpg" alt="网站域名 域名投资 Sex.com 域名抢注" border="0" width="642" title="1406215561-million-dollar-urls-most-expensive-domain-names-of-all-time-fly.jpg" hspace="0" vspace="0" height="369" style="width: 580px; height: 320px;" /></p>
<p><strong>Fly.com&mdash;&mdash;成交价 176 万美元</strong></p>
<p>成交年份：2009 年</p>
<p>Travelzoo 在 2009 年 1 月斥巨资购得 fly.com 域名。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/14092362291F-12MT.jpg" alt="网站域名 域名投资 Sex.com 域名抢注" border="0" width="642" title="1406215663-million-dollar-urls-most-expensive-domain-names-of-all-time-seniors.jpg" hspace="0" vspace="0" height="369" style="width: 580px; height: 320px;" /></p>
<p><strong>Seniors.com&mdash;&mdash;成交价 180 万美元</strong></p>
<p>成交年份：2007 年</p>
<p>2007 年对于这位名叫 Page Howe 的人来说是个很重要的年份。在 2007 年，他卖出了两个值钱的域名。除了这个价值 180 万美元的 Seniors.com 之外，他还以 100 万美元的价格卖出了 Guy.com 域名。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/1409236230060-135555.jpg" alt="网站域名 域名投资 Sex.com 域名抢注" border="0" width="642" title="1406215936-million-dollar-urls-most-expensive-domain-names-of-all-time-37.jpg" hspace="0" vspace="0" height="369" style="width: 580px; height: 320px;" /></p>
<p><strong>37.com&mdash;&mdash;成交价 196 万零 800 美元</strong></p>
<p>成交日期：2014 年 3 月</p>
<p>37.com 域名在 2014 年 3 月以 190 万美元的高价成交。中国游戏制造商 37 玩购得了这个域名。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/140923623050-143205.jpg" alt="网站域名 域名投资 Sex.com 域名抢注" border="0" width="642" title="1406216046-million-dollar-urls-most-expensive-domain-names-of-all-time-computers.jpg" hspace="0" vspace="0" height="369" style="width: 580px; height: 320px;" /></p>
<p><strong>Computer.com&mdash;&mdash;成交价 210 万美元</strong></p>
<p>成交年份：2007 年</p>
<p>在 2007 年 10 月，Computer.com 域名创造了拍卖价格新高。实际上，在当年 WallStreet.com 域名差点以 300 万美元的价格成交，不过依照 DomainRich 的说法，买卖双方并没有达成价格上的共识，因此最终 Computer.com 域名成为了价格新高。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/1409236231020-1545K.jpg" alt="网站域名 域名投资 Sex.com 域名抢注" border="0" width="642" title="1406216131-million-dollar-urls-most-expensive-domain-names-of-all-time--114.jpg" hspace="0" vspace="0" height="369" style="width: 580px; height: 320px;" /></p>
<p><strong>114.com&mdash;&mdash;成交价 210 万美元</strong></p>
<p>成交日期：2013 年 7 月</p>
<p>一家中国公司以 210 万美元的高价购得了 114.com 域名。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/140923623160-1EY9.jpg" alt="网站域名 域名投资 Sex.com 域名抢注" border="0" width="642" title="1406216252-million-dollar-urls-most-expensive-domain-names-of-all-time-kk.jpg" hspace="0" vspace="0" height="369" style="width: 580px; height: 320px;" /></p>
<p><strong>KK.com&mdash;&mdash;成交价 240 万美元</strong></p>
<p>成交日期：2013 年 11 月</p>
<p>Moniker/SnapNames 公司在 2013 年 11 月以 240 万美元的高价售出了 KK.com 域名。</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c140828/14092362153Z-143K.jpg{/dede:field}
