{dede:field name='keywords'}站长之家, Wordpress主题,{/dede:field}
{dede:field name='description'}Bootstrap 是 Twitter 推出的一个开源的用于前端开发的 CSS/HTML 框架，它提供了优雅的HTML和CSS规范，它即是由动态 CSS 语言 Less 写成，Bootstrap 是基于 jQuery 框架开{/dede:field}
{dede:field name='title'}{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p>Bootstrap 是 Twitter 推出的一个开源的用于前端开发的 CSS/HTML 框架，它提供了优雅的HTML和CSS规范，它即是由动态 CSS 语言 Less 写成，Bootstrap 是基于 jQuery 框架开发的，它在 jQuery 框架的基础上进行了更为个性化和人性化的完善，形成一套自己独有的网站风格，今天就给大家推荐 18 个由 Bootstrap 构建的免费 WordPress 主题！</p>
<p><strong>Inkness</strong></p>
<p><img src="/uploads/allimg/c140828/14092361525Z-53320.png" border="0" width="600" alt="Wordpress主题 Bootstrap 网站设计" /></p>
<p>Inkness 是一个支持高清屏的 WordPress 主题，基于网格的主页，和多种页面布局。</p>
<p><a class="visitbutton external" href="http://demo.inkhive.com/inkness/" target="_blank">下载 </a></p>
<p><strong>Fullby</strong></p>
<p><img src="/uploads/allimg/c140828/14092361543Z-D414.jpg" border="0" width="600" alt="Wordpress主题 Bootstrap 网站设计" /></p>
<p>Fullby 是源自默认的 2014 主题，并且使用了 Bootstrap 重构，主页使用瀑布流的方式展示日志，并且顶部还有推荐内容。</p>
<p><a class="visitbutton external" href="http://www.marchettidesign.net/fullby/" target="_blank">下载 </a></p>
<p><strong>WP Knowledge Base</strong></p>
<p><img src="/uploads/allimg/c140828/1409236154960-ON2.jpg" border="0" width="600" alt="Wordpress主题 Bootstrap 网站设计" /></p>
<p>WP Knowledge Base 是一个用于创建多个产品知识库的 WordPress 主题，它包含了多个 Bootstrap 插件，并且支持 bbPress。</p>
<p><a class="visitbutton external" href="http://wordpress.org/themes/wp-knowledge-base" target="_blank">下载 </a></p>
<p><strong>Arcade Basic</strong></p>
<p><img src="/uploads/allimg/c140828/140923615540-QA2.png" border="0" width="600" alt="Wordpress主题 Bootstrap 网站设计" /></p>
<p>Arcade Basic 是一个非常漂亮的主题，重风格的首页，并内置了很多选项到 WordPress 主题定制器。它还支持日志格式，并且对 Jetpack 相册还做了特别的样式。</p>
<p><a class="visitbutton external" href="http://wordpress.org/themes/arcade-basic" target="_blank">下载 </a></p>
<p><strong>Stanley WP</strong></p>
<p><img src="/uploads/allimg/c140828/140923615EZ-91312.png" border="0" width="600" alt="Wordpress主题 Bootstrap 网站设计" /></p>
<p>Stanley WP 是一个非常适合个人品牌风格的主题，它内置了一个拖拉的首页创建器，和三种不同页面模板。</p>
<p><a class="visitbutton external" href="http://gentsthemes.com/themes/stanleywp-twitter-bootstrap-wordpress-theme/" target="_blank">下载 </a></p>
<p><strong>GovFresh WP</strong></p>
<p><img src="/uploads/allimg/c140828/140923615V20-105U0.png" border="0" width="600" alt="Wordpress主题 Bootstrap 网站设计" /></p>
<p>GovFresh 特别为政府部门制作的主题，并且<span class="external">推荐的插件</span>会大大增强主题的功能。</p>
<p><a class="visitbutton external" href="https://github.com/govfresh/govpress">下载 </a></p>
<p><strong>Romangie</strong></p>
<p><img src="/uploads/allimg/c140828/140923615b50-1132W.png" border="0" width="600" alt="Wordpress主题 Bootstrap 网站设计" /></p>
<p>Romangie 是个支持高清屏的主题，支持日志格式，让用户在移动和桌面上都能得到提到非常高质量的用户体验。</p>
<p><a class="visitbutton external" href="http://wordpress.org/themes/romangie" target="_blank">下载 </a></p>
<p><strong>Blain</strong></p>
<p><img src="/uploads/allimg/c140828/1409236161420-12Z91.png" border="0" width="600" alt="Wordpress主题 Bootstrap 网站设计" /></p>
<p>Blain 是一个非常简洁设计的主题，首页有一个响应式的幻灯片，可定制的头部和底部，4种页面布局，和带有缩略图最新日志的 Widget。</p>
<p><a class="visitbutton external" href="http://inkhive.com/product/blain/" target="_blank">下载 </a></p>
<p><strong>Adament</strong></p>
<p><img src="/uploads/allimg/c140828/1409236162D0-1310F.png" border="0" width="600" alt="Wordpress主题 Bootstrap 网站设计" /></p>
<p><a class="visitbutton external" href="http://www.fabthemes.com/adament/" target="_blank">下载 </a></p>
<p><strong>Lobster</strong></p>
<p><img src="/uploads/allimg/c140828/1409236164N0-142117.png" border="0" width="600" alt="Wordpress主题 Bootstrap 网站设计" /></p>
<p>Lobster 主题主要特点是字体，它的背景和页面模板是完全可定制的，并且支持日志格式，bbPress 和 BuddyPress。</p>
<p><a class="visitbutton external" href="http://wordpress.org/themes/lobster" target="_blank">下载 </a></p>
<p><strong>Revera</strong></p>
<p><img src="/uploads/allimg/c140828/14092361A250-155C5.png" border="0" width="600" alt="Wordpress主题 Bootstrap 网站设计" /></p>
<p>Revera 主题首页有个很大的幻灯片，可配置 banner 广告，和自定义的作品页面模板。</p>
<p><a class="visitbutton external" href="http://www.fabthemes.com/revera/" target="_blank">下载 </a></p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c140828/14092361525Z-53320.png{/dede:field}
