
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:phone itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:unit itemname="单位" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:unit>

<field:email itemname="E-mail" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:texts itemname="留言" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:texts>
