<li>
                    	        <span>[field:global.autoindex/].</span>
                                <div class="fEMain">
                        	        <strong><a href="[field:arcurl/]" target="_blank">[field:fulltitle/]</a></strong>
                                    <p>[field:info function="cn_substr(@me,80)"/]...</p>
                                </div>
                                <div class="clear"></div>
                            </li>