{dede:field name='keywords'}北京网站设计,北京网页设{/dede:field}
{dede:field name='description'}藤设计(www.tengsj.com)建站经验丰富，能为您提供北京网站建设、北京网站制作、北京网站设计和上海网站设计、上海网站建设、上海网站制作两地服务，实现企业互联网一站式建站服务。{/dede:field}
{dede:field name='title'}宝尼尔电器LOGO设计{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p>LOGO取首字母“B“为原形，考虑 BNE是做冷柜产品的，所以使用了冷色调，蓝色。为了突显立体和视觉效果，把B用小写的形式，并且模拟氟利昂管道设计；食物不管是肉类还是素菜类都能把冷柜储存，同时在B的背后出现了2个色块 黄色代表肉类、绿色代表素材，都被宝尼尔征服。</p><p><br /></p><p style="TEXT-ALIGN: center"><img alt="" src="/uploads/allimg/c141025/141423453a0-149512.jpg" /><br /></p><p style="TEXT-ALIGN: center"><img alt="" src="/uploads/allimg/c141025/14142345410P-159339.jpg" /><br /></p>{/dede:field}
{dede:field name='gg'}{/dede:field}
{dede:field name='gx'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c141025/1414234541930-1ET0.jpg{/dede:field}
