<div class="iPNTop">
                	<div class="iPNTPic">
                    	<img src="[field:litpic/]" />
                    </div>
                    <div class="iPNPicCont">
                    	<strong><a href="[field:arcurl/]" target="_blank">[field:fulltitle/]</a></strong>
                        <p>
[field:description/]</p>
                    </div>
                    <div class="clear"></div>
                </div>