<?php
$z[0]=Array("field","海云信息",0,53);
$z[0][4]['name']="keywords";
$z[1]=Array("field","海云信息",55,111);
$z[1][4]['name']="description";
$z[2]=Array("field","",113,151);
$z[2][4]['name']="title";
$z[3]=Array("field","",153,192);
$z[3][4]['name']="writer";
$z[4]=Array("field","",194,233);
$z[4][4]['name']="source";
$z[5]=Array("field","",235,272);
$z[5][4]['name']="body";
$z[6]=Array("field","",274,309);
$z[6][4]['name']="gg";
$z[7]=Array("field","",311,346);
$z[7][4]['name']="gx";
$z[8]=Array("field","",348,388);
$z[8][4]['name']="pubdate";
$z[9]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",390,654);
$z[9][4]['name']="imgurls";
$z[10]=Array("field","",656,695);
$z[10][4]['name']="litpic";

?>