<li>
                                    <a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a>
                                    <div class="navHidden">
                                        <div class="subNav">
                                	        <div class="subNLeft">
                                            {dede:type typeid='25'}
                                                 <a href="[field:typelink/]">联系方式</a>{/dede:type}
                                                 {dede:channel}
                                                        <a href="[field:typelink/]">[field:typename/]</a>
                                                    {/dede:channel}
                                                    
                                            </div>
                                            <div class="subPic">
                                                <img alt="" src="/banner/20130729083227_7233.jpg" />
                                            </div>
                                            <div class="clear"></div>
                                        </div>
                                    </div>
                                </li>