<?php
$z[0]=Array("field","",51,79);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",81,110);
$z[1][4]['name']="typename";
$z[2]=Array("type","\r\n                                                 <a href=\"[field:typelink/]\">联系方式</a>",348,478);
$z[2][4]['typeid']="25";
$z[3]=Array("channel","\r\n                                                        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                                                    ",529,719);

?>