{dede:field name='keywords'}站长之家, 网站在线监控{/dede:field}
{dede:field name='description'}我们任何人不能保证自己能够24小时在电脑前，即便我们有选择高富帅VPS主机产品也不能100%的确保不出现任何问题，有些时候可能是服务商机器稳定性问题，也有的时候是我们自{/dede:field}
{dede:field name='title'}{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p>我们任何人不能保证自己能够24小时在电脑前，即便我们有选择高富帅VPS主机产品也不能100%的确保不出现任何问题，有些时候可能是服务商机器稳定性问题，也有的时候是我们自身网站出现问题导致VPS主机的宕机问题。如果我们不能够及时的处理，会给用户带来不良的用户体验，也会影响我们网站的运营状态。</p>
<p>我们可以通过网站监控工具我们的VPS主机，一旦出现问题会有提醒邮件发送给我们，而且可以在平台中管理多台机器/网站，确保我们有足够的效率处理这些问题。在这篇文章中，老左将会分享10款国外免费网站在线监控服务工具，希望有一款能够适合我们VPS主机需要。（排名不分先后）、</p>
<p><strong>第一、UptimeRobot</strong></p>
<p style="text-align: center; text-indent: 0;"><img class="alignnone size-full wp-image-3119" src="/uploads/allimg/c140828/1409236194b0-45152.jpg" border="0" width="645" alt="uptimerobot" height="366" /></p>
<p>这款UptimeRobot（uptimerobot.com）为免费监控工具，提供每5分钟监控一次数据，每个账户我们可以监控50个站点，足够我们使用，如果有更多其他需要那就多注册账户，如果有宕机会可以通过邮件、推特、短信提供到我们。</p>
<p><strong>第二、PingDom</strong></p>
<p style="text-align: center; text-indent: 0;"><img class="alignnone size-full wp-image-3120" src="/uploads/allimg/c140828/1409236195640-59364.jpg" border="0" width="651" alt="pingdom" height="353" /></p>
<p>PingDom（pingdom.com）是一款大家比较熟悉的工具，虽然大部分都需要付费服务，但是基础的监控还是可以使用的，支持一个站点，每个月20个邮件提醒功能，基础的网站还是够用，如果多个站点就需要注册多个账户。或者我们采用付费账户。</p>
<p><strong>第三、Monitor</strong></p>
<p style="text-align: center; text-indent: 0;"><img class="alignnone size-full wp-image-3121" src="/uploads/allimg/c140828/1409236196120-A1Q.jpg" border="0" width="632" alt="monitor" height="260" /></p>
<p>Monitor （monitor.us）提供1个站点/账户，每个30分钟的监控服务，可以发送至邮箱、短信、RSS提醒。</p>
<p><strong>第四、InternetSeer</strong></p>
<p style="text-align: center; text-indent: 0;"><img class="alignnone size-full wp-image-3122" src="/uploads/allimg/c140828/1409236196440-K020.jpg" border="0" width="632" alt="internetseer" height="289" /></p>
<p>InternetSeer（internetseer.com）每个账户提供1个站点监控服务、每小时监控一次，提供SMS、邮件、页面的提醒服务。</p>
<p><strong>第五、Uptrends</strong></p>
<p style="text-align: center; text-indent: 0;"><img class="alignnone size-full wp-image-3123" src="/uploads/allimg/c140828/140923619D40-X612.jpg" border="0" width="627" alt="uptrends" height="335" /></p>
<p>Uptrends（uptrends.com）免费账户提供1个站点监控，30分钟更新一次数据，但只能提供页面动态信息反馈，免费账户不支持邮件和短信提醒功能。</p>{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c140828/1409236194b0-45152.jpg{/dede:field}
