<?php
$z[0]=Array("arcurl","",45,60);
$z[1]=Array("title","",72,86);
$z[2]=Array("title","",95,109);
$z[3]=Array("litpic","",116,131);
$z[4]=Array("arcurl","",205,220);
$z[5]=Array("title","",222,236);
$z[6]=Array("description","",260,321);
$z[6][4]['function']="cn_substr(Html2text(@me),150)";
$z[7]=Array("pubdate","",370,416);
$z[7][4]['function']="GetDateTimeMK(@me)";
$z[8]=Array("click","",436,450);

?>