<dl class="new_list2">
        <dt><a href="[field:arcurl/]"><img alt="[field:title/]" title="[field:title/]" src="[field:litpic/]" height="92" width="149"></a></dt>
        <dd>
          <h2><a href="[field:arcurl/]">[field:title/]</a></h2>
          <p>[field:description function="cn_substr(Html2text(@me),300)"/]...</p>
          <div><ul class="new_info"><li>[field:pubdate function="GetDateTimeMK(@me)"/]</li><li class="ll">[field:click/]</li></ul></div>
        </dd>
      </dl>