{dede:field name='keywords'}站长之家, 网站加载速度{/dede:field}
{dede:field name='description'}来自谷歌的统计数据：网页加载超过4秒，25%的人会放弃；手机网页超过10秒，50%用户会放弃，60%的人不会再返回该网站。亚马逊每天销售额约6700万美元，网页延迟1秒可导致全{/dede:field}
{dede:field name='title'}{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p>来自谷歌的统计数据：网页加载超过4秒，25%的人会放弃；手机网页超过10秒，50%用户会放弃，60%的人不会再返回该网站。亚马逊每天销售额约6700万美元，网页延迟1秒可导致全年最高损失16亿美元。此外，&ldquo;谷歌一代&rdquo;的线下生活也是快节奏的：盗版、快餐、速配、少耐心。</p>
<p style="text-align: center; text-indent: 0;"><img src="/uploads/allimg/c140828/1409236209E0-940a.jpg" border="0" alt="网站加载速度 谷歌搜索引擎 网站优化" /></p>
<p>相关信息：</p>
<p>让用户在你的网站有个愉快的体验并不是件容易的事情 ，是什么让他们在打开你的网页没多久就按下返回键？又是什么让他们为什么那么快就想摆脱你的网站？为此小编总结了15大负面因素一起来看下吧！</p>                    <!-- addon picture_group 124 start -->
<div style="text-align:center;">
    <div class="addon-gallery mod-gallery" id="GALLERY53d71896a822b">
        <div class="gallery-overlay" data-gallery="overlay"></div>
        <div class="gallery-content" data-gallery="content" style="visibility:hidden;">
            <div class="gallery-toolbar">
            <span style="float:right">
                <a href="http://www.chinaz.com/web/2014/0310/342688.shtml" target="_blank">查看完整组图</a>
            </span>
            </div>
            <div class="gallery-photo">
                <div class="gallery-photo-items" data-gallery="photo-items"></div>
                <div class="gallery-photo-prev" data-gallery="photo-prev">
                    <a title="点击浏览上一张图片，支持'←'翻页" href="javascript:void(0);" hideFocus="true">上一页</a>
                </div>
                <div class="gallery-photo-next" data-gallery="photo-next">
                    <a title="点击浏览下一张图片，支持'→'翻页" href="javascript:void(0);" hideFocus="true">下一页</a>
                </div>
                <div class="gallery-loading" data-gallery="loading"><span></span></div>
            </div>
            <div class="gallery-photo-description">
                <p data-gallery="photo-description"></p>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="gallery-footer" data-gallery="footer" style="visibility:hidden;">
            <div class="clearfix">
                <div class="gallery-thumb" data-gallery="slider">
                <span class="gallery-thumb-prev">
                    <a href="javascript:void(0);" hideFocus="true" data-slider="items-left"></a>
                </span>
                <span class="gallery-thumb-next">
                    <a href="javascript:void(0);" hideFocus="true" data-slider="items-right"></a>
                </span>
                    <div class="gallery-thumbs" data-slider="control">
                        <div class="gallery-thumb-list">
                            <ul class="gallery-thumb-items" data-slider="items"></ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
                <script type="text/javascript">
            fet('lib.gallery.white', function() {
                var photos = [];
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442483165.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442483165.jpg',
                    note: ""                });
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442484604.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442484604.jpg',
                    note: ""                });
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442484925.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442484925.jpg',
                    note: ""                });
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442484127.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442484127.jpg',
                    note: ""                });
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442485426.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442485426.jpg',
                    note: ""                });
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442485731.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442485731.jpg',
                    note: ""                });
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442485266.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442485266.jpg',
                    note: ""                });
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442486136.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442486136.jpg',
                    note: ""                });
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442486610.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442486610.jpg',
                    note: ""                });
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442486327.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442486327.jpg',
                    note: ""                });
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442486444.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442486444.jpg',
                    note: ""                });
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442487568.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442487568.jpg',
                    note: ""                });
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442487432.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442487432.jpg',
                    note: ""                });
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442487966.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442487966.jpg',
                    note: ""                });
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442487772.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442487772.jpg',
                    note: ""                });
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442488415.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442488415.jpg',
                    note: ""                });
                                photos.push({
                    big: 'http://upload.chinaz.com/2014/0310/thumb_540_360_1394442488531.jpg',
                    thumb: 'http://upload.chinaz.com/2014/0310/thumb_80_60_1394442488531.jpg',
                    note: ""                });
                                $('#GALLERY53d71896a822b').gallery({
                    photos: photos,
                    maxWidth: parseInt(540) || 0,
                    minHeight: parseInt(360) || 0,
                    preload: 1,
                    scrollIntoView: false,
                    hashPageParam: 'g342688',
                    thumbWidth: parseInt(80) || 80,
                    thumbHeight: parseInt(60) || 60
                });
            });
        </script>
    </div>
</div>
<!-- addon picture_group 124 end -->{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c140828/1409236209E0-940a.jpg{/dede:field}
