<?php
$z[0]=Array("field","北京网站设计,北京网页设",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","藤设计(www.tengsj.com)建站经验丰富，能为您提供北京网站建设、北京网站制作、北京网站设计和上海网站设计、上海网站建设、上海网站制作两地服务，实现企业互联网一站式建站服务。",77,365);
$z[1][4]['name']="description";
$z[2]=Array("field","鸿耀科技企业形象logo设计",367,439);
$z[2][4]['name']="title";
$z[3]=Array("field","",441,480);
$z[3][4]['name']="writer";
$z[4]=Array("field","",482,521);
$z[4][4]['name']="source";
$z[5]=Array("field","",523,563);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","<p>虽然设计了很多款LOGO，但最终还是选择了第一个设计灵感。</p><p style=\"TEXT-ALIGN: center\"><img alt=\"\" src=\"/uploads/allimg/c141025/1414234532350-X362.jpg\" /><br /></p><p>标志设计说明：主要通过鸿耀拼音首字母HY组合而成，为了让视觉有更好的延续性，所以变成了H Yao；</p><p>H Yao解说：通过对鸿耀科技公司的分析，主要产品是智能控制类产品，属于建筑节能产品之一，所以在设计时对整个LOGO进行了深度挖掘，其中H代表着鸿和英文Home（我需要一个家），让用户在使用了鸿耀产品后，家里的感觉舒适、温馨、健康、节能、环保并带有生命力，整个视觉效果像流动的河水（俗话说，企业不是做到有多红火，而是要做到像水一样，一直流淌下去，走的更远，走的更深，最后汇入江河）。<br /></p>",565,1493);
$z[6][4]['name']="body";
$z[7]=Array("field","",1495,1530);
$z[7][4]['name']="gg";
$z[8]=Array("field","",1532,1567);
$z[8][4]['name']="gx";
$z[9]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",1569,1833);
$z[9][4]['name']="imgurls";
$z[10]=Array("field","/uploads/allimg/c141025/14142345335Z-95244.jpg",1835,1920);
$z[10][4]['name']="litpic";

?>