{dede:field name='keywords'}北京网站设计,北京网页设{/dede:field}
{dede:field name='description'}藤设计(www.tengsj.com)建站经验丰富，能为您提供北京网站建设、北京网站制作、北京网站设计和上海网站设计、上海网站建设、上海网站制作两地服务，实现企业互联网一站式建站服务。{/dede:field}
{dede:field name='title'}鸿耀科技企业形象logo设计{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}<p>虽然设计了很多款LOGO，但最终还是选择了第一个设计灵感。</p><p style="TEXT-ALIGN: center"><img alt="" src="/uploads/allimg/c141025/1414234532350-X362.jpg" /><br /></p><p>标志设计说明：主要通过鸿耀拼音首字母HY组合而成，为了让视觉有更好的延续性，所以变成了H Yao；</p><p>H Yao解说：通过对鸿耀科技公司的分析，主要产品是智能控制类产品，属于建筑节能产品之一，所以在设计时对整个LOGO进行了深度挖掘，其中H代表着鸿和英文Home（我需要一个家），让用户在使用了鸿耀产品后，家里的感觉舒适、温馨、健康、节能、环保并带有生命力，整个视觉效果像流动的河水（俗话说，企业不是做到有多红火，而是要做到像水一样，一直流淌下去，走的更远，走的更深，最后汇入江河）。<br /></p>{/dede:field}
{dede:field name='gg'}{/dede:field}
{dede:field name='gx'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c141025/14142345335Z-95244.jpg{/dede:field}
