<?php
$z[0]=Array("channel"," <a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a>",158,264);
$z[0][4]['typeid']="1";
$z[1]=Array("channel"," <a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a>",375,481);
$z[1][4]['typeid']="4";
$z[2]=Array("channel"," <a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a>",580,687);
$z[2][4]['typeid']="11";
$z[3]=Array("channel"," <a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a>",776,883);
$z[3][4]['typeid']="16";
$z[4]=Array("channel"," <a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a>",979,1086);
$z[4][4]['typeid']="22";
$z[5]=Array("type"," <a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a>",1189,1290);
$z[5][4]['typeid']="25";
$z[6]=Array("channel"," <a href=\"[field:typelink/]\" target=\"_blank\">[field:typename/]</a>",1306,1413);
$z[6][4]['typeid']="25";
$z[7]=Array("arclist","\r\n                            <li>\r\n                    	        <span>[field:global.autoindex/].</span>\r\n                                <div class=\"fEMain\">\r\n                        	        <strong><a href=\"[field:arcurl/]\" target=\"_blank\">[field:fulltitle/]</a></strong>\r\n                                    <p>[field:info function=\"cn_substr(@me,80)\"/]...</p>\r\n                                </div>\r\n                                <div class=\"clear\"></div>\r\n                            </li>\r\n                            ",1778,2355);
$z[7][4]['typeid']="28";
$z[7][4]['row']="6";

?>