<?php
$z[0]=Array("type","<a title=\"案例展示\" href=\"[field:typeurl/]\">客户案例</a>",105,203);
$z[0][4]['typeid']="4";
$z[1]=Array("type","<a title=\"资讯动态\" href=\"[field:typeurl/]\">新闻资讯</a>",211,310);
$z[1][4]['typeid']="22";
$z[2]=Array("type","<a title=\"服务项目\" href=\"[field:typeurl/]\">服务项目</a>",318,416);
$z[2][4]['typeid']="1";
$z[3]=Array("type","<a title=\"手机网站建设\" href=\"[field:typeurl/]\">手机建站</a>",424,529);
$z[3][4]['typeid']="11";
$z[4]=Array("type","<a title=\"关于我们\" href=\"[field:typeurl/]\">关于我们</a>",537,636);
$z[4][4]['typeid']="16";
$z[5]=Array("type","<a title=\"联系我们\" rel=\"nofollow\" href=\"[field:typeurl/]\">联系我们</a>",644,758);
$z[5][4]['typeid']="25";

?>