<?php
$z[0]=Array("field","",84,106);
$z[0][4]['name']="typename";
$z[1]=Array("global","",415,441);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",487,513);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("channel","\r\n<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n",643,828);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li class='active'><a href='~typelink~'>~typename~</a></li>";
$z[4]=Array("type","<li><a title=\"案例展示\" href=\"[field:typeurl/]\">案例</a></li>",836,937);
$z[4][4]['typeid']="4";
$z[5]=Array("type","<li><a title=\"资讯动态\" href=\"[field:typeurl/]\">资讯</a></li>",939,1041);
$z[5][4]['typeid']="22";
$z[6]=Array("type","<li><a title=\"服务项目\" href=\"[field:typeurl/]\">服务</a></li>",1043,1144);
$z[6][4]['typeid']="1";
$z[7]=Array("type","<li><a title=\"手机网站建设\" href=\"[field:typeurl/]\">手机</a></li>",1146,1254);
$z[7][4]['typeid']="11";
$z[8]=Array("type","<li><a title=\"关于我们\" href=\"[field:typeurl/]\">关于</a></li>",1256,1358);
$z[8][4]['typeid']="16";
$z[9]=Array("type","<li><a title=\"联系我们\" rel=\"nofollow\" href=\"[field:typeurl/]\">联系</a></li>",1360,1477);
$z[9][4]['typeid']="25";

?>