<?php
$z[0]=Array("field","",258,277);
$z[0][4]['name']="title";
$z[1]=Array("global","",278,304);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",345,367);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",407,458);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1462,1497);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1783,1812);
$z[5][4]['name']="position";
$z[6]=Array("field","",1952,1973);
$z[6][4]['name']="content";
$z[7]=Array("channel","\r\n                            <li><a href=\"[field:typelink/]\" class=\"active\">[field:typename/]</a></li>\r\n                        ",2194,2435);
$z[7][4]['type']="son";
$z[7][4]['typeid']="11";
$z[7][4]['currentstyle']="<li><a href='~typelink~'>~typename~</a> </li>";
$z[8]=Array("include","",3209,3247);
$z[8][4]['filename']="footer1.htm";
$z[9]=Array("include","",3251,3288);
$z[9][4]['filename']="footer.htm";

?>