<?php
$z[0]=Array("global","",252,278);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",322,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,416);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",999,1036);
$z[3][4]['filename']="header.htm";
$z[4]=Array("type","  <h2>科研设计：</h2>\r\n           <div><a href=\"[field:typeurl/]\" target=\"_blank\"><img src=\"/images/jianzhan1.jpg\" alt=\"科研设计：\"></a></div>\r\n           <p>针对调查研究、试验设计、量表开发及其他科研项目中涉及的统计学、流行病学等问题，提供专业的统计学指导和服务，包括样本量计算、抽样方式、方案设计、调查表设计、现场调查及数据收集等方面提供专业咨询和服务，帮助以较少的人力、物力和时间，换取最大的成果。\r\n</p><samp><a href=\"[field:typeurl/]\" target=\"_blank\">了解更多</a></samp>\r\n           ",2197,2856);
$z[4][4]['typeid']="2";
$z[5]=Array("type","\r\n<h2>现场调查：</h2>\r\n<div><a href=\"[field:typeurl/]\" target=\"_blank\"><img src=\"/images/jianzhan2.jpg\" alt=\"品牌型网站定制方案\"></a></div>\r\n<p>在科研项目中涉及现场调查时，公司将以第三方立场提供现场调查服务。需求者只需提供调查方案，公司将组织具有丰富经验的专业技术人员进行现场调查。</p><samp><a href=\"[field:typeurl/]\" target=\"_blank\">了解更多</a></samp>\r\n",2880,3357);
$z[5][4]['typeid']="3";
$z[6]=Array("type","\r\n<h2>数据处理和挖掘:</h2>\r\n<div><a href=\"[field:typeurl/]\" target=\"_blank\"><img src=\"/images/jianzhan3.jpg\" alt=\"电商型网站定制方案\"></a></div>\r\n<p>应用专业的数据处理软件，为复杂、混乱、多噪声、海量的各类型数据提供专业的录入与处理，便于查看检索和统计分析。数据处理后，根据客户的需求，从海量数据中挖掘潜在的价值，以清晰明了的报告展示出来。</p><samp><a href=\"[field:typeurl/]\" target=\"_blank\">了解更多</a></samp>\r\n",3374,3937);
$z[6][4]['typeid']="29";
$z[7]=Array("type"," <div class=\"min_nav_left\"><a style=\"float:right;\" href=\"[field:typeurl/]\">了解更多>></a><a href=\"javascript:void(0)\" class=\"hov\">收费说明</a></div>",4484,4675);
$z[7][4]['typeid']="33";
$z[8]=Array("include","",8069,8106);
$z[8][4]['filename']="footer.htm";

?>