<?php
$z[0]=Array("global","",252,278);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",322,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,416);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("field","",1064,1086);
$z[3][4]['name']="typename";
$z[4]=Array("include","",1343,1380);
$z[4][4]['filename']="header.htm";
$z[5]=Array("type","<a href=\"[field:typelink/]\" class=\"hov\" title=\"全部新闻\"><font>全部资讯</font></a>",2035,2159);
$z[5][4]['typeid']="4";
$z[6]=Array("channel"," \r\n <a href='[field:typelink/]'><font>[field:typename/]</font></a>\r\n",2169,2291);
$z[6][4]['typeid']="22";
$z[6][4]['type']="son";
$z[7]=Array("list","\r\n            <dl class=\"new_list2\">\r\n        <dt><a href=\"[field:arcurl/]\"><img alt=\"[field:title/]\" title=\"[field:title/]\" src=\"[field:litpic/]\" height=\"92\" width=\"149\"></a></dt>\r\n        <dd>\r\n          <h2><a href=\"[field:arcurl/]\">[field:title/]</a></h2>\r\n          <p>[field:description function=\"cn_substr(Html2text(@me),300)\"/]...</p>\r\n          <div><ul class=\"new_info\"><li>[field:pubdate function=\"GetDateTimeMK(@me)\"/]</li><li class=\"ll\">[field:click/]</li></ul></div>\r\n        </dd>\r\n      </dl>\r\n",2459,3006);
$z[7][4]['pagesize']="10";
$z[8]=Array("pagelist","",3146,3224);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",3282,3319);
$z[9][4]['filename']="footer.htm";

?>