<?php
$z[0]=Array("field","",264,283);
$z[0][4]['name']="title";
$z[1]=Array("global","",284,310);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",351,373);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",413,464);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1468,1503);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1780,1809);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n                                    		<span><a href=\"[field:typelink/]\">[field:typename/]</a></span>",1906,2134);
$z[6][4]['typeid']="4";
$z[6][4]['currentstyle']="<a href='~typelink~' class='active' ~rel~><span>~typename~</span></a>";
$z[7]=Array("list","\r\n                            <li>\r\n                    	        <a href=\"[field:arcurl/]\" target=\"_blank\">\r\n                        	        <em></em>\r\n                        	        <img src=\"[field:litpic/]\" />\r\n                                    <div class=\"picLText\">\r\n                            	        <p>[field:title/]</p>\r\n                                        <span>Hits:    <script src=\"/plus/count.php?view=yes&aid=[field:id/]&mid=1\" type='text/javascript' language=\"javascript\"></script> Date:[field:pubdate function=\"MyDate('Y',@me)\"/]</span>\r\n                                    </div>\r\n                                </a>\r\n                            </li>",2363,3080);
$z[7][4]['pagesize']="12";
$z[8]=Array("pagelist","",3251,3329);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",3483,3521);
$z[9][4]['filename']="footer1.htm";
$z[10]=Array("include","",3525,3562);
$z[10][4]['filename']="footer.htm";

?>