<?php
$z[0]=Array("global","",252,278);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",322,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,416);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",999,1036);
$z[3][4]['filename']="header.htm";
$z[4]=Array("type","  <h2>宣传型网站设计方案</h2>\r\n           <div><a href=\"[field:typeurl/]\" target=\"_blank\"><img src=\"/images/jianzhan1.jpg\" alt=\"宣传型网站定制方案\"></a></div>\r\n           <p>为中、小型企业在网上宣传打开了新渠道，通过搜索引擎能找到自己的企业。价格实惠，性能比较优越，适用于想通过网站建设进行企业宣传和客户服务的小型企业或想尝试网站效果的中、小型企业。</p>\r\n           <h3>￥3000</h3><samp><a href=\"[field:typeurl/]\" target=\"_blank\">了解更多</a></samp>\r\n           ",1844,2452);
$z[4][4]['typeid']="2";
$z[5]=Array("type","\r\n<h2>品牌型网站设计方案</h2>\r\n<div><a href=\"[field:typeurl/]\" target=\"_blank\"><img src=\"/images/jianzhan2.jpg\" alt=\"品牌型网站定制方案\"></a></div>\r\n<p>网站页面设计精美，打造品牌化的运营模式，提升公司的整体形象和特点；适用于想通过网站建设宣传企业产品与服务，提升行业形象，扩大品牌影响，拓展潜在市场的品牌营销性企业。</p><h3>￥6000</h3><samp><a href=\"[field:typeurl/]\" target=\"_blank\">了解更多</a></samp>\r\n",2476,3020);
$z[5][4]['typeid']="3";
$z[6]=Array("type","\r\n<h2>电商型网站设计方案</h2>\r\n<div><a href=\"[field:typeurl/]\" target=\"_blank\"><img src=\"/images/jianzhan3.jpg\" alt=\"电商型网站定制方案\"></a></div>\r\n<p>网站以引导客户选购商品为目的，合理的导购设计，商品展示内容充分、结构清晰，人性化的商品检索与客服服务，并可实现在线付款功能，营造良好的用户购物体验，适用于快消品企业使用。</p><h3>￥8000</h3><samp><a href=\"[field:typeurl/]\" target=\"_blank\">了解更多</a></samp>\r\n",3037,3591);
$z[6][4]['typeid']="29";
$z[7]=Array("type","\r\n<h2>功能型网站设计方案</h2>\r\n<div><a href=\"[field:typeurl/]\" target=\"_blank\"><img src=\"/images/jianzhan4.jpg\" alt=\"功能型网站定制方案\"></a></div>\r\n<p>为满足用户需求，结合每家企业特有品牌形象及营销理念而量身定制企业网站。比如：门户网站开发、企业管理系统开发、大型商城系统开发等，适合大、中、小型企业自定义宣传网站。</p><h3>￥1万起</h3><samp><a href=\"[field:typeurl/]\" target=\"_blank\">了解更多</a></samp>\r\n",3608,4156);
$z[7][4]['typeid']="30";
$z[8]=Array("type"," <div class=\"min_nav_left\"><a style=\"float:right;\" href=\"[field:typeurl/]\">了解更多>></a><a href=\"javascript:void(0)\" class=\"hov\">设计服务</a></div>",4198,4389);
$z[8][4]['typeid']="33";
$z[9]=Array("type","<div class=\"min_nav_left\" style=\"margin-top:20px;\"><a style=\"float:right;\" href=\"[field:typeurl/]\">了解更多>></a><a href=\"javascript:void(0)\" class=\"hov\">SEO优化推广</a></div>",4832,5050);
$z[9][4]['typeid']="31";
$z[10]=Array("include","",9109,9146);
$z[10][4]['filename']="footer.htm";

?>