<?php
$z[0]=Array("global","",252,278);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",322,352);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",389,416);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("field","",1063,1085);
$z[3][4]['name']="typename";
$z[4]=Array("include","",1342,1379);
$z[4][4]['filename']="header.htm";
$z[5]=Array("type","<a href=\"[field:typelink/]\" class=\"hov\" title=\"全部下载\"><font>资料下载</font></a>",2406,2530);
$z[5][4]['typeid']="4";
$z[6]=Array("channel"," \r\n <a href='[field:typelink/]'><font>[field:typename/]</font></a>\r\n",2540,2661);
$z[6][4]['typeid']="4";
$z[6][4]['type']="son";
$z[7]=Array("list","\r\n             <li class=\"group\">\r\n            <div class=\"dribbble\">\r\n                <div class=\"dribbble-shot\">\r\n                    <div class=\"dribbble-img\">\r\n<a href=\"[field:arcurl/]\"><img alt=\"[field:title/]\" title=\"[field:title/]\" src=\"[field:litpic/]\" height=\"170\" width=\"275\"></a>                    </div>\r\n                </div>\r\n            </div>\r\n            <h2><a rel=\"contact\" class=\"url\" href=\"[field:arcurl/]\">[field:title/]</a></h2>\r\n            <p>[field:description function=\"cn_substr(Html2text(@me),120)\"/]...</p>\r\n        </li>\r\n",2831,3422);
$z[7][4]['pagesize']="9";
$z[8]=Array("pagelist","",3596,3674);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",3758,3795);
$z[9][4]['filename']="footer.htm";

?>