<?php
$z[0]=Array("field","",266,285);
$z[0][4]['name']="title";
$z[1]=Array("global","",286,312);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",353,375);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",415,466);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1471,1506);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1783,1812);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n                                    		<span><a href=\"[field:typelink/]\">[field:typename/]</a></span>",1909,2138);
$z[6][4]['typeid']="11";
$z[6][4]['currentstyle']="<a href='~typelink~' class='active' ~rel~><span>~typename~</span></a>";
$z[7]=Array("list","\r\n                            <li>\r\n                    	        <a href=\"[field:arcurl/]\" target=\"_blank\">\r\n                        	        <em></em>\r\n                        	        <img src=\"[field:litpic/]\" />\r\n                                    <div class=\"picLText\">\r\n                            	        <p>[field:title/]</p>\r\n                                        <span>Hits:    <script src=\"/plus/count.php?view=yes&aid=[field:id/]&mid=1\" type='text/javascript' language=\"javascript\"></script> Date:[field:pubdate function=\"MyDate('Y',@me)\"/]</span>\r\n                                    </div>\r\n                                </a>\r\n                            </li>",2367,3084);
$z[7][4]['pagesize']="12";
$z[8]=Array("pagelist","",3255,3333);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",3490,3523);
$z[9][4]['filename']="bo.htm";
$z[10]=Array("include","",3580,3618);
$z[10][4]['filename']="footer1.htm";
$z[11]=Array("include","",3622,3659);
$z[11][4]['filename']="footer.htm";

?>